
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: knowledge_sharing_development

test:
  <<: *default
  database: knowledge_sharing_test

production:
  <<: *default
  database: knowledge_sharing_production
  username: knowledge_sharing
  password: <%= ENV['KNOWLEDGE_SHARING_DATABASE_PASSWORD'] %>
